### ISSUE TITLE
Make "Labs" larger in logo on titlebar

### ISSUE THREAD

**Issue by rgommers** [Quansight-Labs/quansight-labs-site#102]
See the logo at left top here:

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/98330/88576673-13669700-d046-11ea-8287-5904e5831eb5.png">

Troy suggested that LABS is too small, and it'd be better to reverse the font sizes of "Quansight" and "Labs". He also said it's not a logo he recognized; I think you created it @koliphan2?

It's located at `files/images/quansight_labs_logo_white.png`.

**Comment by koliphan2** [comment]
This is just a completely white logo of the logo already in the repo. Because we were going with a simpler color scheme, and the original had purple, green, and orange, I made it completely white so we could actually see what it was. Here was the original one I found in the repo. 
![quansight_labs_logo](https://user-images.githubusercontent.com/35544523/88581114-edbb9c80-d009-11ea-9022-d1fe8c09e7d9.png)

It is still there in the files, just called quansight_labs_logo.png instead. I didn't edit the design at all.

**Comment by rgommers** [comment]
Okay, thanks for that! I forgot the details, and apparently so did Troy.

Let's leave it as is for now then, I don't think we need a tweak right now.

**Comment by troy-bailey** [comment]
That is old artwork that I didn’t know was there. I have created a new flask that we use in other place. We also have a font that works better with the Quansight logo. I will create a new lock-up with those elements and provide an all white one.

**Comment by rgommers** [comment]
That sounds good to me, thanks @troy-bailey

**Comment by melissawm** [comment]
With the new logo, I'm assuming this is not relevant anymore. Is that the case? Thanks!

**Comment by rgommers** [comment]
indeed, no longer relevant, thanks
