### ISSUE TITLE
Check update in projects page with sponsors

### ISSUE THREAD

**Issue by juanis2112** [Quansight-Labs/quansight-labs-site#213]
Before updating the projects page in labs website we should check with the sponsors if they are okay with us mentioning them and if there is a specific way in which they would want to be mentioned.

- [ ] D.E. Shaw
- [ ]  TDK-Micronas
- [ ] #214
- [ ] OmniSci

@rgommers  and @trallard I can check with Tom for TDK. Let me know if you want me to check with Adam for Kite and if there is anyone I can talk to for D.E. Shaw and OmniSci.

Also please let me know if I'm missing anyone.

**Comment by rgommers** [comment]
I'm not 100% sure about this - we mention sponsors on the front page and in blog posts, isn't that enough? 

For D. E. Shaw it would requite review and sign-off from them each time we make a change, which isn't great. On blog posts it's better, because those get reviewed once and will never change after.

**Comment by trallard** [comment]
updating from last conversations we had: we will leave sponsors for now as it is (in the front page) and we will evaluate also on a per blogpost basis shall these be "sponsored" or requested by one of our sponsors

**Comment by trallard** [comment]
Closing since this will no longer be applicable with the website migration 🚀
