### ISSUE TITLE
the daily Cloudflare deploy failed

### ISSUE THREAD

**Issue by rgommers** [Quansight-Labs/quansight-labs-site#256]
See https://github.com/Quansight-Labs/quansight-labs-site/runs/3686326346?check_suite_focus=true

**Comment by trallard** [comment]
I tried to re-trigger from the dashboard and it seems the issue is within CloudFare

https://dash.cloudflare.com/9622d54c36a1e17e88362814b5b08a07/pages/view/quansight-labs-site/7fed3875-ef79-46f3-a0b8-ff74a8a322e2

Also manually called the webook and this failed too - will keep tabs on it and try again later today

**Comment by trallard** [comment]
I re-created the project in CloudFare pages and now triggering the hook works ([see this action](https://github.com/Quansight-Labs/quansight-labs-site/actions/runs/1269282415)) so will wait for the daily build time and hopefully all will be working 🤞🏽

**Comment by trallard** [comment]
This is working again as expected 🎉  https://github.com/Quansight-Labs/quansight-labs-site/actions/runs/1269485993

Closing now
